version: '3'
services:
    mysql_knex:
        container_name: mysql
        hostname: mysql
        image: mysql
        restart: always
        command:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --innodb_force_recovery=0
        ports:
            - 3306:3306
        volumes:
            - ~/.MySQLDBData/mysqlonly/mysql_knex:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: abcdef
            MYSQL_DATABASE: GIBannerCreator
            MYSQL_USER: user
            MYSQL_PASSWORD: abcdef
            TZ: America/Sao_Paulo
